# Generated by Django 4.0.4 on 2022-05-08 15:12

import API.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_on', models.TextField(max_length=100)),
                ('certificate_Id', models.IntegerField()),
                ('certificate_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(max_length=40)),
                ('passing_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), API.models.max_value_current_year])),
                ('School_College', models.TextField(max_length=100)),
                ('Specializaion', models.TextField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Experience', models.IntegerField(default=1)),
                ('Your_Designation', models.TextField(default='Designation You have Worked With', max_length=50)),
                ('your_organization', models.TextField(default='Your Orzanization name', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Describe_job_profile', models.TextField(default='Explain About Your Job', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Online_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_name', models.TextField(blank=True, choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Github', 'Github')], max_length=20)),
                ('Social_url', models.URLField()),
                ('Description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('DOB', models.DateField()),
                ('Phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=100)),
                ('Town', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.TextField(max_length=30)),
                ('Project_Description', models.TextField(max_length=100)),
                ('Project_Lcation', models.TextField(max_length=50)),
                ('Team_Size', models.IntegerField()),
                ('Team_Role', models.TextField(max_length=200)),
                ('Technology_used', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SampleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_title', models.TextField(verbose_name=100)),
                ('Work_link', models.URLField()),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tech_Skill', models.TextField(default='', max_length=100)),
                ('Non_Tech_Skill', models.TextField(default='', max_length=100)),
                ('Description', models.TextField(default='', max_length=100)),
                ('Experience', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
