# Generated by Django 4.0.4 on 2022-05-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdetail',
            name='phone_number',
            field=models.IntegerField(blank=True, help_text='Contact phone number'),
        ),
    ]
