# Generated by Django 4.0.4 on 2022-05-13 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_pdetail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', '.doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='pdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
