# Generated by Django 4.0.4 on 2022-05-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_delete_educations_delete_project_delete_samplework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdetail',
        ),
    ]
