# Generated by Django 4.0.4 on 2022-05-10 06:18

import API.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_pdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(max_length=40)),
                ('passing_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), API.models.max_value_current_year])),
                ('School_College', models.TextField(max_length=100)),
                ('Specializaion', models.TextField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
