# Generated by Django 4.0.4 on 2022-05-10 06:26

import API.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_educations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.TextField(max_length=30)),
                ('Project_Description', models.TextField(max_length=100)),
                ('Project_Lcation', models.TextField(max_length=50)),
                ('Team_Size', models.IntegerField()),
                ('Team_Role', models.TextField(max_length=200)),
                ('Technology_used', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='educations',
            name='passing_year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), API.models.max_value_current_year]),
        ),
    ]
