# Generated by Django 4.0.4 on 2022-05-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_project_alter_educations_passing_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_title', models.TextField(verbose_name=100)),
                ('Work_link', models.URLField()),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_Lcation',
            new_name='Project_Location',
        ),
    ]
