# Generated by Django 4.0.4 on 2022-05-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_samplework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('DOB', models.DateField()),
                ('Phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=100)),
                ('Town', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='samplework',
            name='Work_title',
            field=models.TextField(max_length=100),
        ),
    ]
