# Generated by Django 4.0.4 on 2022-05-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_pdetail_alter_samplework_work_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdetail',
        ),
    ]
