# Generated by Django 4.0.4 on 2022-05-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
