# Generated by Django 4.0.4 on 2022-05-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_fileupload_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='choose_file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='Document',
            field=models.FileField(default=1, upload_to='uploads/documents/'),
            preserve_default=False,
        ),
    ]
