# Generated by Django 4.0.4 on 2022-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_remove_fileupload_choose_file_fileupload_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fileupload',
        ),
        migrations.AddField(
            model_name='employement',
            name='Document',
            field=models.FileField(default=1, upload_to='uploads/documents/'),
            preserve_default=False,
        ),
    ]
