# Generated by Django 4.0.4 on 2022-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_delete_fileupload_employement_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=255)),
                ('Document', models.FileField(upload_to='uploads/documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employement',
            name='Document',
        ),
    ]
